CREATE TABLE notice
(id INT AUTO_INCREMENT, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL,
subcategory VARCHAR(100) NOT NULL, description VARCHAR(400) NOT NULL, foto VARCHAR(400) NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id));
